/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import ADT.LAttendance;
import ADT.LDeliveryman;
import ADT.List;
import Entity.Attendance;
import Entity.Delivery;
import Entity.Deliveryman;
import Entity.FoodOrder;
import Interface.AttendanceInterface;
import Interface.DeliverymanInterface;
import Interface.ListInterface;

/**
 *
 * @author ADmin
 */
public class HomePage extends javax.swing.JFrame {
    
    public static DeliverymanInterface<Deliveryman> deliverymanList = new LDeliveryman<>();
    public static DeliverymanInterface<Delivery> deliveryList = new LDeliveryman<>();
    public static AttendanceInterface<Attendance> attendanceList = new LAttendance<>();
    public static ListInterface<FoodOrder> list = new List<>();    
    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
        Deliveryman newDeliveryMan1 = new Deliveryman("D1001","QY","971008-56-5092","012-2222222","qy@gmail.com","test","23/12/2017",null,"Part-Time");
        Deliveryman newDeliveryMan2 = new Deliveryman("D1002","WZ","950518-56-5092","012-3333333","wz@gmail.com","test","23/12/2017",null,"Full-Time");
        Deliveryman newDeliveryMan3 = new Deliveryman("D1003","WS","952133-56-5092","012-2222222","ws@gmail.com","test","23/12/2017",null,"Retired");
        Delivery delivery1 = new Delivery("D1001","QY",null);
        Delivery delivery2 = new Delivery("D1002","WZ","O1001");
        Delivery delivery3 = new Delivery("D1003","WS","O1002");
        Attendance newAttendance1 = new Attendance("D1001","QY",null,null,"Available",null);
        Attendance newAttendance2 = new Attendance("D1002","WZ",null,null,"Available",null);
        Attendance newAttendance3 = new Attendance("D1003","Bryan",null,null,"Available",null);
        Attendance newAttendance4 = new Attendance("D1004","WS",null,null,"Available",null);
        FoodOrder newFoodOrder1 = new FoodOrder(1001, "MCD", 12.50, 1,25.00,null);
        FoodOrder newFoodOrder2 = new FoodOrder(1002, "Chicken", 12.50, 1,25.00,null);
        
        attendanceList.addRecord(newAttendance1);
        attendanceList.addRecord(newAttendance2);
        attendanceList.addRecord(newAttendance3);
        attendanceList.addRecord(newAttendance4);
        deliverymanList.addRecord(newDeliveryMan1);
        deliverymanList.addRecord(newDeliveryMan2);
        deliverymanList.addRecord(newDeliveryMan3);
        deliveryList.addRecord(delivery1);
        deliveryList.addRecord(delivery2);
        deliveryList.addRecord(delivery3);
        list.add(newFoodOrder1);
        list.add(newFoodOrder2);
        
        System.out.println(deliverymanList);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtRegistration = new javax.swing.JButton();
        jbtSelectToUpdate = new javax.swing.JButton();
        jbtCheckPending = new javax.swing.JButton();
        jbtnClockIn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jbtnAssignJob = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtRegistration.setText("Register Deliveryman");
        jbtRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRegistrationActionPerformed(evt);
            }
        });

        jbtSelectToUpdate.setText("Select To Update");
        jbtSelectToUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSelectToUpdateActionPerformed(evt);
            }
        });

        jbtCheckPending.setText("Check Pending Deliveries");
        jbtCheckPending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCheckPendingActionPerformed(evt);
            }
        });

        jbtnClockIn.setText("ClockIn ClockOut");
        jbtnClockIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnClockInActionPerformed(evt);
            }
        });

        jButton1.setText("TrackStatus");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbtnAssignJob.setText("Assign Job");
        jbtnAssignJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAssignJobActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnAssignJob)
                    .addComponent(jButton1)
                    .addComponent(jbtnClockIn)
                    .addComponent(jbtCheckPending)
                    .addComponent(jbtSelectToUpdate)
                    .addComponent(jbtRegistration))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jbtnAssignJob)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtRegistration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtSelectToUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtCheckPending)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnClockIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRegistrationActionPerformed
        new DeliveryManRegistration().setVisible(true);
    }//GEN-LAST:event_jbtRegistrationActionPerformed

    private void jbtSelectToUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSelectToUpdateActionPerformed
        new ManageDeliveryman().setVisible(true);
    }//GEN-LAST:event_jbtSelectToUpdateActionPerformed

    private void jbtCheckPendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCheckPendingActionPerformed
        new CheckPendingDelivery().setVisible(true);
    }//GEN-LAST:event_jbtCheckPendingActionPerformed

    private void jbtnClockInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnClockInActionPerformed
        new ClockInClockOut().setVisible(true);
    }//GEN-LAST:event_jbtnClockInActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new TrackStatus().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnAssignJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAssignJobActionPerformed
        new AssignDeliveryJob().setVisible(true);
    }//GEN-LAST:event_jbtnAssignJobActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jbtCheckPending;
    private javax.swing.JButton jbtRegistration;
    private javax.swing.JButton jbtSelectToUpdate;
    private javax.swing.JButton jbtnAssignJob;
    private javax.swing.JButton jbtnClockIn;
    // End of variables declaration//GEN-END:variables
}
